const path = require("path");
const { spawnSync } = require("child_process");

const pluginRoot = __dirname;
const vaultRoot = path.resolve(pluginRoot, "..", "..", "..");
const fallbackDependencyRoot = process.env.LLM_WIKI_SYNC_DEPS_ROOT ?? "";

const childCode = `
const fs = require("fs");
const path = require("path");
const { createRequire } = require("module");
const pluginRoot = process.argv[1];
const fallbackDependencyRoot = process.argv[2];
function requireBuildDependency(name) {
  try {
    return createRequire(path.join(pluginRoot, "package.json"))(name);
  } catch (error) {
    if (!fallbackDependencyRoot) {
      throw new Error("Missing build dependency '" + name + "'. Run npm install in the plugin folder, or set LLM_WIKI_SYNC_DEPS_ROOT to a folder where it is installed.");
    }
    return createRequire(path.join(fallbackDependencyRoot, "package.json"))(name);
  }
}
const esbuild = requireBuildDependency("esbuild");
const builtins = requireBuildDependency("builtin-modules");
const result = esbuild.buildSync({
  banner: { js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */" },
  entryPoints: [path.join(pluginRoot, "main.ts")],
  absWorkingDir: pluginRoot,
  bundle: true,
  external: [
    "obsidian", "electron",
    "@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands",
    "@codemirror/language", "@codemirror/lint", "@codemirror/search",
    "@codemirror/state", "@codemirror/view", "@lezer/common", "@lezer/highlight",
    "@lezer/lr", ...builtins
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: false,
  treeShaking: true,
  outfile: "main.js",
  write: false,
  minify: true
});
const output = result.outputFiles && result.outputFiles[0] && result.outputFiles[0].text;
if (!output) throw new Error("Build failed: esbuild did not return output text");
const outputPath = path.join(pluginRoot, "main.js");
fs.writeFileSync(outputPath, output, "utf8");
const written = fs.readFileSync(outputPath, "utf8");
if (!written.includes("THIS IS A GENERATED/BUNDLED FILE BY ESBUILD")) throw new Error("Build output verification failed");
console.log("Wrote " + outputPath + " (" + written.length + " bytes)");
`;

const result = spawnSync(process.execPath, ["-e", childCode, pluginRoot, fallbackDependencyRoot], {
  cwd: vaultRoot,
  stdio: "inherit"
});
process.exit(result.status ?? 1);
