import process from "process";
import path from "path";
import { readFileSync, watch } from "fs";
import { createRequire } from "module";
import { execFileSync } from "child_process";

const production = process.argv[2] === "production";
const workingDirectory = process.cwd();
const entryFile = path.join(workingDirectory, "main.ts");
const outputFile = path.join(workingDirectory, "main.js");
const vaultRoot = path.resolve(workingDirectory, "..", "..", "..");
const fallbackDependencyRoot = process.env.LLM_WIKI_SYNC_DEPS_ROOT ?? "";

function requireBuildDependency(name) {
  const localRequire = createRequire(path.join(workingDirectory, "package.json"));
  try {
    return localRequire(name);
  } catch (error) {
    if (!fallbackDependencyRoot) {
      throw new Error(`Missing build dependency '${name}'. Run npm install in the plugin folder, or set LLM_WIKI_SYNC_DEPS_ROOT to a folder where it is installed.`);
    }
    const fallbackRequire = createRequire(path.join(fallbackDependencyRoot, "package.json"));
    return fallbackRequire(name);
  }
}

const esbuild = requireBuildDependency("esbuild");
const builtins = requireBuildDependency("builtin-modules");

const buildOptions = {
  banner: {
    js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */"
  },
  absWorkingDir: workingDirectory,
  entryPoints: [entryFile],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  write: false,
  minify: production
};

function writeOutputWithRetry(filePath, output) {
  let lastError;
  for (let attempt = 1; attempt <= 20; attempt += 1) {
    try {
      execFileSync(
        process.execPath,
        ["-e", "const fs=require('fs'); fs.writeFileSync(process.argv[1], fs.readFileSync(0,'utf8'), 'utf8');", filePath],
        {
          cwd: vaultRoot,
          input: output,
          stdio: ["pipe", "inherit", "inherit"]
        }
      );
      return;
    } catch (error) {
      lastError = error;
      Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 100);
    }
  }
  throw lastError;
}
async function rebuild() {
  const result = await esbuild.build(buildOptions);
  const output = result.outputFiles?.[0]?.text;
  if (!output) {
    throw new Error("Build failed: esbuild did not return output text");
  }
  writeOutputWithRetry(outputFile, output);
  const written = readFileSync(outputFile, "utf8");
  if (!written.includes("THIS IS A GENERATED/BUNDLED FILE BY ESBUILD")) {
    throw new Error("Build output verification failed: generated banner not found");
  }
  console.log(`Wrote ${path.relative(workingDirectory, outputFile)} (${written.length} bytes)`);
}

if (production) {
  await rebuild();
} else {
  await rebuild();
  console.log("watching TypeScript files...");
  const watcher = watch(workingDirectory, { persistent: true, recursive: true }, (_eventType, filename) => {
    if (filename && filename.endsWith(".ts")) {
      rebuild().catch((error) => {
        console.error(error);
      });
    }
  });
  process.on("SIGINT", () => {
    watcher.close();
    process.exit(0);
  });
}


